name: Waka Readme Daily Update

on:
  workflow_dispatch: 
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Update WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }} 
          GH_TOKEN: ${{ secrets.GH_TOKEN }} 
          SHOW_TITLE: true 
          SECTION_NAME: waka 
          BLOCKS: "=>-"
          TIME_RANGE: last_7_days 
          LANG_COUNT: 5 
          SHOW_TIME: true 
          SHOW_TOTAL: true 
          SHOW_MASKED_TIME: false 
          STOP_AT_OTHER: true 
          COMMIT_MESSAGE: "Updated WakaTime stats in README" 
          SHOW_OS: true 
          SHOW_EDITORS: true 
          SHOW_PROJECTS: true 
          SHOW_BEST_LANGUAGE: true 
